# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Diya Saraf"
title_separator          : "-"
name                     : &name "Diya Saraf"
description              : &description "Misinformation researcher and MSCS student at USC"
url                      : "https://ds257.github.io"
baseurl                  : ""
repository               : "ds257/ds257.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Diya Saraf"
  pronouns         : "she/her"  
  bio              : "MS in Computer Science at USC. Passionate about misinformation research, AI, and social impact."
  location         : "Los Angeles, California"
  employer         : "University of Southern California"
  uri              : 
  email            : "diyasaraf2001@gmail.com" 

  # Academic websites
  academia         : 
  arxiv            : 
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : 
  orcid            : "https://orcid.org/0000-0003-1234-5678"
  semantic         : 
  pubmed           : 
  researchgate     : 
  scopus           : 

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "ds257"
  kaggle           :   
  stackoverflow    :   

  # Social media
  artstation       : 
  bluesky          : "bsky.app"
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "diyasaraf"
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 
